// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5L_wWWaZCuO-tFNX8S5Gsrnk-K2ZkP4w',
    appId: '1:870032839384:web:830c2dc90f20028f82bdad',
    messagingSenderId: '870032839384',
    projectId: 'jars-c19f8',
    authDomain: 'jars-c19f8.firebaseapp.com',
    storageBucket: 'jars-c19f8.appspot.com',
    measurementId: 'G-W5016H23M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDotmCHv4RsQdjaPosHw77HmU-d6_jFm1o',
    appId: '1:870032839384:android:a9294dc8b156274b82bdad',
    messagingSenderId: '870032839384',
    projectId: 'jars-c19f8',
    storageBucket: 'jars-c19f8.appspot.com',
  );
}
